name: Build and test

on:
  push:
    branches:
    - 'master'
    - 'release-*'
  # Run on branch/tag creation
  create:
  # Run on pull requests
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check formatting
        run: ./gradlew spotlessCheck
      - name: Build with Gradle
        run: ./gradlew build
      - name: Read Android lint results
        uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: DeviceSDKAndroid/build/reports/lint-results.xml
