name: Docs generation for Github Pages

on:
  push:
    branches:
    - 'master'
    - 'release-*'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source
      - uses: actions/checkout@v2
        with:
          path: astarte-device-sdk-java
      # Checkout the docs repository
      - uses: actions/checkout@v2
        with:
          repository: astarte-platform/docs
          ssh-key: ${{ secrets.DOCS_DEPLOY_KEY }}
          path: docs
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Generate Javadocs with Gradle
        working-directory: ./astarte-device-sdk-java
        run: ./gradlew aggregateJavadocs
      - name: Copy Docs
        run: |
          export DOCS_DIRNAME="$(echo ${{ github.ref }} | sed 's,refs/heads/,,' | sed 's/master/snapshot/g' | sed 's/release-//g')/device-sdks/java"
          rm -rf docs/$DOCS_DIRNAME
          mkdir -p docs/$DOCS_DIRNAME
          cp -r astarte-device-sdk-java/build/docs/javadoc/* docs/$DOCS_DIRNAME/
      - name: Commit files
        working-directory: ./docs
        run: |
          git config --local user.email "astarte-machine@ispirata.com"
          git config --local user.name "Astarte Bot"
          git add .
          git commit -m "Update Java SDK documentation"
      - name: Push changes
        working-directory: ./docs
        run: |
          git push origin master
